### ISSUE TITLE
"String to Main Model" node is broken in InvokeAI 4.2

### ISSUE THREAD

**Issue by testertestertesttesttester** [skunkworxdark/XYGrid_nodes#6]
I can't connect the "String to Main Model" node to the "Main Model Input" node.

I used Invoke 4.2 and the latest version of this repo.

![broken](https://github.com/skunkworxdark/XYGrid_nodes/assets/169855487/bb3ad788-8f5e-46e5-bab5-70ff07503370)

**Comment by skunkworxdark** [comment]
This is a recent limitation with Invoke.  I have raised a bug on invoke repo https://github.com/invoke-ai/InvokeAI/issues/6380

**Comment by skunkworxdark** [comment]
@testertestertesttesttester 
As a temporary workaround, you could switch off the validate connections option while you connect the noodle and then switch it back on.

![image](https://github.com/skunkworxdark/XYGrid_nodes/assets/21961335/20f510b1-ae26-4474-a790-d2ca2f24fa5c)

**Comment by skunkworxdark** [comment]
Issue was fixed in invoke
